### ISSUE TITLE
Can'nt controll by touch

### ISSUE THREAD

**Issue by Mappaschreck** [masonicGIT/pacman#5]
On the N4 I can't controller pacman by swiping the touchscreen.

**Comment by cibersheep** [comment]
It happens the same on Ubuntu Touch (on mobile) since we start using Morph browser (based on Chromium).
Tapping on a button is ok
Swaping to move Pacaman is ignored

**Comment by qyalexwen** [comment]
I'd like to change the control keys to ADWS, or JLIK  instead of the direction keys. How can I do it?  Thanks.

**Comment by masonicGIT** [comment]
Please recreate this issue with steps to reproduce.
