### ISSUE TITLE
Links to "dossier" broken - is this alternate source the same document ?

### ISSUE THREAD

**Issue by shearichard** [masonicGIT/pacman#7]
The README contains a number of references to the "Pacman dossier" but the links are now broken. 

I found this https://www.gamasutra.com/view/feature/132330/the_pacman_dossier.php?page=1 which could be the same document. 

If it is I would be happy to change the links in the README and do a PR but, obviously, it would be best if someone who's familiar with the document could confirm it's the same thing. Can anyone confirm that ... or suggest a better source ?

**Comment by masonicGIT** [comment]
Yes that's it.

Please feel free to do a PR, would be appreciated.
