### ISSUE TITLE
what is the use of spritesheet.png?

### ISSUE THREAD

**Issue by upq** [masonicGIT/pacman#8]
I noticed that the graphics are drawn using code in the game, my questions are
What is the use of the spritesheet.png file?
And how may I edit the graphics in the game, change player character and ghost charecters?

Thank you so much, very clean and well done work!

**Comment by vincent-bartissol** [comment]
You can edit charecters in file sprites.js, and use canvas draw from svg file. Insert canvas draw un function like drawPacmanSprite for main caracter.

no idea of use of spritesheet.png

**Comment by upq** [comment]
Thank you for taking time to answer :) honestly the issue is so old that I don't even remember what I wanted to do with it :D but thank you so much I appreciate your time.
